name = "kollector-images"
main = "./index.js"
compatibility_date = "2026-01-01"
account_id = "1c96409b15483aeb26499da3e9a1cb2b"
workers_dev = true

r2_buckets = [
  { binding = "COVERS", bucket_name = "cover-art-staging" }
]
